### ISSUE TITLE
Scss 常用工具类 mixins

### ISSUE THREAD

**Issue by huguangju** [huguangju/blog#1]
### 溢出文本显示省略号

``` scss
@mixin ellipsis($clamp: 1, $line-height: null, $width: null) {
  @if $width {
    max-width: $width;
  }
  @else {
    max-width: 100%;
  }
  overflow: hidden;
  text-overflow: ellipsis;

  @if $clamp == 1 {
    word-wrap: normal;
    white-space: nowrap;
  }
  @else if $clamp > 1 {
    display: -webkit-box;
    @if $line-height {
      max-height: $line-height * $clamp;
      line-height: $line-height;
    }
    word-wrap: break-word;
    white-space: normal;
    -webkit-line-clamp: $clamp;
    -webkit-box-orient: vertical;
  }
}
```

### 边距、间距工具类生成

```scss
@mixin spacing-gen ($spacers, $direction) {
  @each $prop, $abbrev in (margin: m, padding: p) {
    // 消除间距，.m0, .p0
    .#{$abbrev}0 {
      #{$prop}: 0px !important;
    }

    @each $size in $spacers {
      // 不带方向的间距，如 .p1, .p2, .p3 ...; .m1, .m2, .m3 ...
      .#{$abbrev}#{$size} {
        #{$prop}: $size + px !important;
      }

      @each $dir-abbrev, $dir in $direction {
        // 带方向的间距，如 .pt1, .pr1, .pt2 ...; .mt1, .mr1, .mt2 ...
        .#{$abbrev}#{$dir-abbrev}#{$size} {
          #{$prop}-#{$dir}: $size + px !important;
        }
      }
    }
  }
}
```

> 使用如下

```scss
// 注：$spacers 列表可调整，但不应太长，以避免生成过多冗余类
$direction: (t: top, r: right, b: bottom, l: left);
$spacers: 1, 2, 5, 10, 15, 20, 30, 40, 50;
@include spacing-gen($spacers, $direction);
```

### 宽度工具类

```scss
@mixin width-gen ($size) {
  @each $s in $size {
    .w#{$s} {
      width: $s + px;
    }
  }
}
```

> 使用如下

``` scss
$widthList: 100, 150, 200, 300, 350, 400, 500, 600, 700;
@include width-gen($widthList);
```
